[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "chmod +x ./build-app.sh && sh ./build-app.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
APP_ENV = "production"
APP_DEBUG = "false"
CACHE_DRIVER = "redis"
QUEUE_CONNECTION = "redis"
SESSION_DRIVER = "redis"
LOG_CHANNEL = "errorlog"
APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
FORCE_HTTPS = "true"

[[services]]
name = "web"
envs = ["PORT"]
scale = 2

[[services]]
name = "queue"
command = "chmod +x ./run-worker.sh && sh ./run-worker.sh"
envs = ["PORT"]
scale = 2
healthcheckPath = "/api/health"

[[services]]
name = "cron"
command = "chmod +x ./run-cron.sh && sh ./run-cron.sh"
envs = ["PORT"] 